name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make

    - name: Add MSYS2 to PATH
      run: echo "C:\\msys64\\mingw64\\bin" >> $env:GITHUB_PATH
      shell: pwsh

    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" -B build
      env:
        VERBOSE: 1

    - name: Build
      run: mingw32-make -C build
      env:
        VERBOSE: 1

    - name: Run tests
      run: build\test_task.exe --success
      env:
        VERBOSE: 1


